package ru.forgethedragon.ftdadditions.handlers;

import net.minecraft.item.Item;
import net.minecraftforge.common.util.EnumHelper;
import ru.forgethedragon.ftdadditions.common.items.*;
import ru.forgethedragon.ftdadditions.common.items.bases.*;
import ru.forgethedragon.ftdadditions.common.items.wands.WandRunicCap;
import ru.forgethedragon.ftdadditions.common.items.wands.WandRunicRod;
import ru.forgethedragon.ftdadditions.helpers.ItemRegisterHelper;
import thaumcraft.api.wands.WandCap;
import thaumcraft.api.wands.WandRod;

import static com.mark719.magicalcrops.handlers.ModCompat.farmland;
import static ru.forgethedragon.ftdadditions.common.CommonProxy.*;

public class FTDItems {

    public static final Item.ToolMaterial toolMaterialUltimate = EnumHelper.addToolMaterial("Ultimate", 8, -1, 50F, 30F, 30);

    public static final Item emblemDragon = new FinalEmblem("DragonEmblem", "emblem_dragon", "DragonEmblem");
    public static final Item emblemStar = new FinalEmblem("StarEmblem", "emblem_star", "StarEmblem");
    public static final Item fragmentChaos = new FTDItem("ChaosFragment", "fragment_chaos");
    public static final Item dustBrick = new FTDItem("BrickDust", "dust_brick");
    public static final Item dustNetherBrick = new FTDItem("NetherBrickDust", "dust_nether_brick");
    public static final Item dustBurntBrick = new FTDItem("BurntBrickDust", "dust_burnt_brick");
    public static final Item blendCoke = new FTDItem("CokeBlend", "blend_coke");
    public static final Item blendFireproof = new FTDItem("FireproofBlend", "blend_fireproof");
    public static final Item blendHighQuality = new FTDItem("HighQualityBlend", "blend_high_quality");
    public static final Item brickCoke = new FTDItem("CokeBrick", "brick_coke");
    public static final Item brickFireproof = new FTDItem("FireproofBrick", "brick_fireproof");
    public static final Item brickSmeltery = new FTDItem("SmelteryBrick", "brick_smeltery");
    public static final Item ingotChaotic = new FTDItem("ChaoticIngot", "ingot_chaotic");
    public static final Item sheetCarbon = new FTDItem("CarbonSheet", "sheet_carbon");
    public static final Item sheetPlastic = new FTDItem("PlasticSheet", "sheet_plastic");
    public static final Item seedsRubber = new FTDMagicSeed(FTDBlocks.cropRubber, farmland, "RubberSeeds", "seeds_rubber");
    public static final Item seedsGraphite = new FTDMagicSeed(FTDBlocks.cropGraphite, farmland, "GraphiteSeeds", "seeds_graphite");
    public static final Item seedsMeteor = new FTDMagicSeed(FTDBlocks.cropMeteor, farmland, "MeteorSeeds", "seeds_meteor");
    public static final Item seedsDesh = new FTDMagicSeed(FTDBlocks.cropDesh, farmland, "DeshSeeds", "seeds_desh");
    public static final Item seedsTitan = new FTDMagicSeed(FTDBlocks.cropTitan, farmland, "TitanSeeds", "seeds_titan");
    public static final Item seedsVoid = new FTDMagicSeed(FTDBlocks.cropVoid, farmland, "VoidSeeds", "seeds_void");
    public static final Item seedsGaia = new FTDMagicSeed(FTDBlocks.cropGaia, farmland, "GaiaSeeds", "seeds_gaia");
    public static final Item seedsEfirium = new FTDMagicSeed(FTDBlocks.cropEfirium, farmland, "EfiriumSeeds", "seeds_efirium");
    public static final Item seedsNetherStar = new FTDMagicSeed(FTDBlocks.cropNetherStar, farmland, "NetherStarSeeds", "seeds_nether_star");
    public static final Item seedsAwakenedDraconium = new FTDMagicSeed(FTDBlocks.cropAwakenedDraconium, farmland, "AwakenedDraconiumSeeds", "seeds_awakened_draconium");
    public static final Item seedsCosmic = new FTDMagicSeed(FTDBlocks.cropCosmic, farmland, "CosmicSeeds", "seeds_cosmic");
    public static final Item essenceAbsolutio = new FTDItem("AbsolutioEssence", "essence_absolutio");
    public static final Item essenceRubber = new FTDItem("RubberEssence", "essence_rubber");
    public static final Item essenceGraphite = new FTDItem("GraphiteEssence", "essence_graphite");
    public static final Item essenceMeteor = new FTDItem("MeteorEssence", "essence_meteor");
    public static final Item essenceDesh = new FTDItem("DeshEssence", "essence_desh");
    public static final Item essenceTitan = new FTDItem("TitanEssence", "essence_titan");
    public static final Item essenceVoid = new FTDItem("VoidEssence", "essence_void");
    public static final Item essenceGaia = new FTDItem("GaiaEssence", "essence_gaia");
    public static final Item essenceEfirium = new FTDItem("EfiriumEssence", "essence_efirium");
    public static final Item essenceNetherStar = new FTDItem("NetherStarEssence", "essence_nether_star");
    public static final Item essenceAwakenedDraconium = new FTDItem("AwakenedDraconiumEssence", "essence_awakened_draconium");
    public static final Item essenceCosmic = new FTDItem("CosmicEssence", "essence_cosmic");
    public static final Item coreCorruption = new FTDItemGlow("CorruptionCore", "core_corruption");
    public static final Item quantumModuleCompression = new FTDItem("CompressionQuantumModule", "quantum_module_compression");
    public static final Item quantumModuleInfinity = new FTDItem("InfinityQuantumModule", "quantum_module_infinity");
    public static final Item runicRod = new FTDItem("RunicRod", "runic_rod");
    public static final Item runicCap = new FTDItem("RunicCap", "runic_cap");
    public static final ItemHeart heartChaotic = new ChaoticHeart("ChaoticHeart", "heart_chaotic");
    public static final Item solderingIron = new SolderingIron("SolderingIron", "soldering_iron");
    public static final Item amuletAntiCorruption = new AmuletAntiCorruption("AmuletAntiCorruption", "amulet_anti_corruption");
    public static final WandRod wandRunicRod = new WandRunicRod();
    public static final WandCap wandRunicCap = new WandRunicCap();
    public static final Item circuitBaseBasic = new FTDItem("BasicCircuitBase", "circuit_base_basic");
    public static final Item circuitBaseAdvanced = new FTDItem("AdvancedCircuitBase", "circuit_base_advanced");
    public static final Item circuitBasePerfect = new FTDItem("PerfectCircuitBase", "circuit_base_perfect");
    public static final Item controlChipBasic = new FTDItem("BasicControlChip", "control_chip_basic");
    public static final Item controlChipAdvanced = new FTDItem("AdvancedControlChip", "control_chip_advanced");
    public static final Item controlChipPerfect = new FTDItem("PerfectControlChip", "control_chip_perfect");
    public static final Item transistorBasic = new FTDItem("BasicTransistor", "transistor_basic");
    public static final Item transistorAdvanced = new FTDItem("AdvancedTransistor", "transistor_advanced");
    public static final Item transistorPerfect = new FTDItem("PerfectTransistor", "transistor_perfect");
    public static final Item circuitAdvanced = new FTDItem("AdvancedCircuit", "circuit_advanced");
    public static final Item circuitQuantum = new FTDItem("QuantumCircuit", "circuit_quantum");
    public static final Item circuitPerfect = new FTDItem("PerfectCircuit", "circuit_perfect");
    public static final Item combsCosmic = new FTDItem("CosmicCombs", "combs_cosmic");
    public static final Item coreEnergyChaotic = new FTDItem("ChaoticEnergyCore", "core_energy_chaotic");
    public static final Item researchPackageScientific = new ResearchPackage("ScientificResearchPackage", "info.ResearchPackage.0.name");
    public static final Item researchPackageMagical = new ResearchPackage("MagicalResearchPackage", "info.ResearchPackage.1.name");
    public static final Item researchPackageIndustrial = new ResearchPackage("IndustrialResearchPackage", "info.ResearchPackage.2.name");
    public static final Item researchPackageChemical = new ResearchPackage("ChemicalResearchPackage", "info.ResearchPackage.3.name");
    public static final Item researchPackageAuto = new ResearchPackage("AutoResearchPackage", "info.ResearchPackage.4.name");
    public static final Item researchPackageQuantum = new ResearchPackage("QuantumResearchPackage", "info.ResearchPackage.5.name");
    public static final Item researchPackageDraconic = new ResearchPackage("DraconicResearchPackage", "info.ResearchPackage.6.name");
    public static final Item wateringCanUltimate = new AdvancedWateringCan();
    public static final Item researchBookCrops = new ResearchBook("CropsResearchBook", "research_book_crops", cropsResearchBookFirst, cropsResearchBookSecond, "info.ResearchBook.0.name");
    public static final Item researchBookAvaritia = new ResearchBook("AvaritiaResearchBook", "research_book_avaritia", avaritiaResearchBookFirst, avaritiaResearchBookSecond, "info.ResearchBook.1.name");

    public static void registerItem() {
        ItemRegisterHelper.registerItem(FTDItems.emblemDragon);
        ItemRegisterHelper.registerItem(FTDItems.emblemStar);
        ItemRegisterHelper.registerItem(FTDItems.dustBrick);
        ItemRegisterHelper.registerItem(FTDItems.dustNetherBrick);
        ItemRegisterHelper.registerItem(FTDItems.dustBurntBrick);
        ItemRegisterHelper.registerItem(FTDItems.blendCoke);
        ItemRegisterHelper.registerItem(FTDItems.blendFireproof);
        ItemRegisterHelper.registerItem(FTDItems.blendHighQuality);
        ItemRegisterHelper.registerItem(FTDItems.brickCoke);
        ItemRegisterHelper.registerItem(FTDItems.brickFireproof);
        ItemRegisterHelper.registerItem(FTDItems.brickSmeltery);
        ItemRegisterHelper.registerItem(FTDItems.sheetCarbon);
        ItemRegisterHelper.registerItem(FTDItems.sheetPlastic);
        ItemRegisterHelper.registerItem(FTDItems.quantumModuleCompression);
        ItemRegisterHelper.registerItem(FTDItems.quantumModuleInfinity);
        ItemRegisterHelper.registerItem(FTDItems.circuitBaseBasic);
        ItemRegisterHelper.registerItem(FTDItems.circuitBaseAdvanced);
        ItemRegisterHelper.registerItem(FTDItems.circuitBasePerfect);
        ItemRegisterHelper.registerItem(FTDItems.controlChipBasic);
        ItemRegisterHelper.registerItem(FTDItems.controlChipAdvanced);
        ItemRegisterHelper.registerItem(FTDItems.controlChipPerfect);
        ItemRegisterHelper.registerItem(FTDItems.transistorBasic);
        ItemRegisterHelper.registerItem(FTDItems.transistorAdvanced);
        ItemRegisterHelper.registerItem(FTDItems.transistorPerfect);
        ItemRegisterHelper.registerItem(FTDItems.circuitAdvanced);
        ItemRegisterHelper.registerItem(FTDItems.circuitQuantum);
        ItemRegisterHelper.registerItem(FTDItems.circuitPerfect);
        ItemRegisterHelper.registerItem(FTDItems.combsCosmic);
        ItemRegisterHelper.registerItem(FTDItems.fragmentChaos);
        ItemRegisterHelper.registerItem(FTDItems.ingotChaotic);
        ItemRegisterHelper.registerItem(FTDItems.coreCorruption);
        ItemRegisterHelper.registerItem(FTDItems.heartChaotic);
        ItemRegisterHelper.registerItem(FTDItems.coreEnergyChaotic);
        ItemRegisterHelper.registerItem(FTDItems.solderingIron);
        ItemRegisterHelper.registerItem(FTDItems.runicRod);
        ItemRegisterHelper.registerItem(FTDItems.runicCap);
        ItemRegisterHelper.registerItem(FTDItems.amuletAntiCorruption);
        ItemRegisterHelper.registerItem(FTDItems.seedsRubber);
        ItemRegisterHelper.registerItem(FTDItems.seedsGraphite);
        ItemRegisterHelper.registerItem(FTDItems.seedsMeteor);
        ItemRegisterHelper.registerItem(FTDItems.seedsDesh);
        ItemRegisterHelper.registerItem(FTDItems.seedsTitan);
        ItemRegisterHelper.registerItem(FTDItems.seedsVoid);
        ItemRegisterHelper.registerItem(FTDItems.seedsGaia);
        ItemRegisterHelper.registerItem(FTDItems.seedsEfirium);
        ItemRegisterHelper.registerItem(FTDItems.seedsNetherStar);
        ItemRegisterHelper.registerItem(FTDItems.seedsAwakenedDraconium);
        ItemRegisterHelper.registerItem(FTDItems.seedsCosmic);
        ItemRegisterHelper.registerItem(FTDItems.essenceAbsolutio);
        ItemRegisterHelper.registerItem(FTDItems.essenceRubber);
        ItemRegisterHelper.registerItem(FTDItems.essenceGraphite);
        ItemRegisterHelper.registerItem(FTDItems.essenceMeteor);
        ItemRegisterHelper.registerItem(FTDItems.essenceDesh);
        ItemRegisterHelper.registerItem(FTDItems.essenceTitan);
        ItemRegisterHelper.registerItem(FTDItems.essenceVoid);
        ItemRegisterHelper.registerItem(FTDItems.essenceGaia);
        ItemRegisterHelper.registerItem(FTDItems.essenceEfirium);
        ItemRegisterHelper.registerItem(FTDItems.essenceNetherStar);
        ItemRegisterHelper.registerItem(FTDItems.essenceAwakenedDraconium);
        ItemRegisterHelper.registerItem(FTDItems.essenceCosmic);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageScientific);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageMagical);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageIndustrial);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageChemical);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageAuto);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageQuantum);
        ItemRegisterHelper.registerItem(FTDItems.researchPackageDraconic);
        ItemRegisterHelper.registerItem(FTDItems.wateringCanUltimate);
        ItemRegisterHelper.registerItem(FTDItems.researchBookCrops);
        ItemRegisterHelper.registerItem(FTDItems.researchBookAvaritia);
    }
}
